CREATE TABLE SHIP (
SHIP_ID  INT PRIMARY KEY AUTO_INCREMENT,
SHIP_NAME VARCHAR(60),
SHIP_SIZE VARCHAR(30),
SHIP_TYPE VARCHAR(30),
SHIP_IMG VARCHAR(120),
SHIP_CAPACITY VARCHAR(60));

INSERT INTO SHIP(SHIP_NAME,SHIP_SIZE,SHIP_TYPE,SHIP_IMG,SHIP_CAPACITY) VALUES('荣超','60','游艇',' ','14');


CREATE TABLE SHIP_OPERATION  (
SHIP_ID INT PRIMARY KEY AUTO_INCREMENT,
SHIP_NAME VARCHAR(60),
STARTIME DATE,
SHIP_ROLE INT(1),
ADMIN_NAME VARCHAR(40));
INSERT INTO SHIP_OPERATION(SHIP_NAME,STARTIME,SHIP_ROLE,ADMIN_NAME) VALUES('荣超',NOW(),2,'小爷');

CREATE TABLE ADMIN_INFO(
   	ADMIN_ID 	 INT PRIMARY KEY AUTO_INCREMENT,
   	ADMIN_CODE 	VARCHAR(30) NOT NULL,
   	PASSWORD 	VARCHAR(30) NOT NULL,
   	NAME 		VARCHAR(30) NOT NULL,
   	TELEPHONE 	VARCHAR(15),
   	EMAIL 		VARCHAR(50),
   	QQ			VARCHAR(15),
   	ADDRESS		VARCHAR(120),
   	GENDER		INT(1),
   	ENROLLDATE 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO ADMIN_INFO(ADMIN_CODE,PASSWORD,NAME,TELEPHONE,EMAIL,QQ,ADDRESS,GENDER) VALUES('ADMIN','LKAILYT','ADMIN','18676660220','RABBITS@LIVE.CN','464020173','湖南省长沙市天心区里仁坡新二栋',1);

CREATE TABLE ADMIN_ROLE(
	ADMIN_ID	INT(8) NOT NULL,
  	ROLE_ID		INT(4) NOT NULL,
  	CONSTRAINT ADMIN_ROLE_PK PRIMARY KEY(ADMIN_ID,ROLE_ID)
);
INSERT INTO ADMIN_ROLE VALUES(1,100);
INSERT INTO ADMIN_ROLE VALUES(1,200);
INSERT INTO ADMIN_ROLE VALUES(1,300);

CREATE TABLE ROLE_MODULE(
ROLE_ID INT(4) NOT NULL,
MODULE_ID INT(4) NOT NULL,
CONSTRAINT ROLE_MODULE_PK PRIMARY KEY(ROLE_ID,MODULE_ID));

INSERT INTO ROLE_MODULE VALUES(100,2);
INSERT INTO ROLE_MODULE VALUES(200,3);
INSERT INTO ROLE_MODULE VALUES(300,4);
COMMIT;

CREATE TABLE ROLE_INFO(
		ROLE_ID		INT(4) ,CONSTRAINT ROLE_INFO_ID_PK PRIMARY KEY(ROLE_ID),
		NAME	VARCHAR(50) 	NOT NULL
);
INSERT INTO ROLE_INFO VALUES(100,'管理员');
INSERT INTO ROLE_INFO VALUES(200,'普通会员');
INSERT INTO ROLE_INFO VALUES(300,'付费会员');


CREATE TABLE MODULE_INFO(
	MODULE_ID INT(4) ,CONSTRAINT MODULE_INFO_ID_PK PRIMARY KEY(MODULE_ID),
	NAME VARCHAR(50) NOT NULL
	);
	
INSERT INTO MODULE_INFO VALUES(1,'角色管理');
INSERT INTO MODULE_INFO VALUES(2,'管理员');
INSERT INTO MODULE_INFO VALUES(3,'普通会员模块');
INSERT INTO MODULE_INFO VALUES(4,'付费会员模块');
INSERT INTO MODULE_INFO VALUES(5,'业务帐号');
INSERT INTO MODULE_INFO VALUES(6,'账单管理');
INSERT INTO MODULE_INFO VALUES(7,'报表');

--IMG
CREATE TABLE IMAGE_INFO(
IMG_ID INT PRIMARY KEY AUTO_INCREMENT,
IMG_TYPE VARCHAR(60),
IMG_SIZE VARCHAR(30),
IMG_NAME VARCHAR(60),
IMG_PATH VARCHAR(100));

--NEWS
CREATE TABLE NEWS(
NEWS_ID INT PRIMARY KEY AUTO_INCREMENT,
NEWS_TITLE VARCHAR(120),
NEWS_TEXT VARCHAR(21845),
NEWS_IMG VARCHAR(30),
NEWS_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP);


----触发器---
CREATE TRIGGER TR_SHIP_INSERT_AFTER AFTER INSERT ON SHIP FOR EACH ROW INSERT INTO DATESHIP(DATESHIP_NAME) VALUES (NEW.SHIP_NAME);

CREATE TABLE DATESHIP(
DATESHIP_ID INT PRIMARY KEY AUTO_INCREMENT,
DATESHIP_NAME VARCHAR(60) NOT NULL,
T1 INT(1)DEFAULT 0,
T2 INT(1)DEFAULT 0,
T3 INT(1)DEFAULT 0,
T4 INT(1)DEFAULT 0,
T5 INT(1)DEFAULT 0,
T6 INT(1)DEFAULT 0,
T7 INT(1)DEFAULT 0,
T8 INT(1)DEFAULT 0,
T9 INT(1)DEFAULT 0,
T10 INT(1)DEFAULT 0,
T11 INT(1)DEFAULT 0,
T12 INT(1)DEFAULT 0,
T13 INT(1)DEFAULT 0,
T14 INT(1)DEFAULT 0,
T15 INT(1)DEFAULT 0,
T16 INT(1)DEFAULT 0,
T17 INT(1)DEFAULT 0,
T18 INT(1)DEFAULT 0,
T19 INT(1)DEFAULT 0,
T20 INT(1)DEFAULT 0,
T21 INT(1)DEFAULT 0,
T22 INT(1)DEFAULT 0,
T23 INT(1)DEFAULT 0,
T24 INT(1)DEFAULT 0,
FOREIGN KEY(DATESHIP_NAME) REFERENCES SHIP(SHIP_NAME)
ON DELETE CASCADE ON UPDATE CASCADE);